### ISSUE TITLE
v1.0.0-alpha1

### ISSUE THREAD

**Issue by bookchin** [bookchin/granax#1]
### TODO

* [x] PROTOCOLINFO
* [x] AUTHENTICATE
* [x] AUTHCHALLENGE
  * [x] COOKIE
  * [x] SAFECOOKIE
* [x] ADD_ONION
* [x] DEL_ONION
* [x] SETCONF
* [x] RESETCONF
* [x] GETCONF
* [x] SETEVENTS
  * EventEmitter interface
* [x] SAVECONF
* [x] SIGNAL
* [x] MAPADDRESS
* [x] GETINFO
* [x] EXTENDCIRCUIT
* [x] SETCIRCUITPURPOSE
* [x] ~SETROUTERPURPOSE~ - deprecated
* [x] ATTACHSTREAM
* [x] POSTDESCRIPTOR
* [x] REDIRECTSTREAM
* [x] CLOSESTREAM
* [x] CLOSECIRCUIT
* [x] QUIT
* [x] ~USEFEATURE~ - always enabled in tor 2.x
* [x] RESOLVE
* [x] LOADCONF
* [x] TAKEOWNERSHIP
* [x] DROPGUARDS
* [x] HSFETCH
* [x] HSPOST

**Comment by bookchin** [comment]
* [ ] More robust authentication api
  * support no token
  * support hash control pass
  * constructor options for defining with strategy
* [ ] Update docs, tutorials, etc
  * Outline platform and config specific info
